PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0

# Set all versions
PALYRIM_BUILD_TYPE ?= UNOFFICIAL
PALYRIM_FLAVOR := Tiramisu
PALYRIM_CODE := 1.0
ANDROID_CODE := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

# Internal version
LINEAGE_VERSION := PalyrimOS-$(PALYRIM_CODE)-$(LINEAGE_BUILD)-$(PALYRIM_BUILD_TYPE)-$(PALYRIM_VARIANT)-$(shell date +%Y%m%d)

# Display version
LINEAGE_DISPLAY_VERSION := $(PALYRIM_CODE)-$(LINEAGE_BUILD)-$(PALYRIM_BUILD_TYPE)-$(PALYRIM_VARIANT)-$(shell date +%Y%m%d)